-- MySQL Script generated by MySQL Workbench
-- Seg 09 Out 2017 22:19:45 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema u856889270_eedom
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `u856889270_eedom` ;

-- -----------------------------------------------------
-- Schema u856889270_eedom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `u856889270_eedom` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `u856889270_eedom` ;

-- -----------------------------------------------------
-- Table `u856889270_eedom`.`tb_clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u856889270_eedom`.`tb_clientes` ;

CREATE TABLE IF NOT EXISTS `u856889270_eedom`.`tb_clientes` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(400) NULL COMMENT '',
  `usuario` VARCHAR(100) NULL COMMENT '',
  `email` VARCHAR(200) NULL COMMENT '',
  `senha` VARCHAR(32) NULL COMMENT '',
  `nacionalidade` VARCHAR(200) NULL COMMENT '',
  `estado_civil` CHAR(1) NULL COMMENT 'S - Solteiro, C - Casado, V - Viuvo e U - Uniao Estavel',
  `profissao` VARCHAR(200) NULL COMMENT '',
  `dt_nascimento` DATE NULL COMMENT '',
  `rg` VARCHAR(25) NULL COMMENT '',
  `cpf` BIGINT(11) NULL COMMENT '',
  `titulo_eleitor` VARCHAR(40) NULL COMMENT '',
  `esocial` VARCHAR(100) NULL COMMENT '',
  `esocial_senha` VARCHAR(200) NULL COMMENT '',
  `ativo` VARCHAR(45) NULL COMMENT 'S - Sim ou Não',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = MyISAM DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `u856889270_eedom`.`tb_funcionarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u856889270_eedom`.`tb_funcionarios` ;

CREATE TABLE IF NOT EXISTS `u856889270_eedom`.`tb_funcionarios` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(200) NULL COMMENT '',
  `rg` VARCHAR(40) NULL COMMENT '',
  `cpf` BIGINT(11) NULL COMMENT '',
  `titulo_eleitor` VARCHAR(40) NULL COMMENT '',
  `id_clientes` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_tb_funcionarios_tb_clientes_idx` (`id_clientes` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_funcionarios_tb_clientes`
    FOREIGN KEY (`id_clientes`)
    REFERENCES `u856889270_eedom`.`tb_clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = MyISAM DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `u856889270_eedom`.`tb_arquivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u856889270_eedom`.`tb_arquivos` ;

CREATE TABLE IF NOT EXISTS `u856889270_eedom`.`tb_arquivos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo` VARCHAR(100) NULL COMMENT '',
  `descricao` VARCHAR(200) NULL COMMENT '',
  `arquivo` BLOB NULL COMMENT '',
  `dt_cadastro` DATE NULL COMMENT '',
  `id_funcionarios` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_tb_arquivos_tb_funcionarios1_idx` (`id_funcionarios` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_arquivos_tb_funcionarios1`
    FOREIGN KEY (`id_funcionarios`)
    REFERENCES `u856889270_eedom`.`tb_funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = MyISAM DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `u856889270_eedom`.`tb_servicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u856889270_eedom`.`tb_servicos` ;

CREATE TABLE IF NOT EXISTS `u856889270_eedom`.`tb_servicos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(200) NULL COMMENT '',
  `obs` LONGTEXT NULL COMMENT '',
  `valor` FLOAT(10,2) NULL COMMENT '',
  `dt_cadastro` DATE NULL COMMENT '',
  `id_clientes` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_tb_servicos_tb_clientes1_idx` (`id_clientes` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_servicos_tb_clientes1`
    FOREIGN KEY (`id_clientes`)
    REFERENCES `u856889270_eedom`.`tb_clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = MyISAM DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `u856889270_eedom`.`tb_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u856889270_eedom`.`tb_admin` ;

CREATE TABLE IF NOT EXISTS `u856889270_eedom`.`tb_admin` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(200) NULL COMMENT '',
  `email` VARCHAR(200) NULL COMMENT '',
  `senha` VARCHAR(32) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = MyISAM DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `u856889270_eedom`.`tb_faturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u856889270_eedom`.`tb_faturas` ;

CREATE TABLE IF NOT EXISTS `u856889270_eedom`.`tb_faturas` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nro_transcao` VARCHAR(100) NULL COMMENT '',
  `dt_vencimento` DATE NULL COMMENT '',
  `dt_cadastro` DATE NULL COMMENT '',
  `valor` FLOAT(10,2) NULL COMMENT '',
  `status` CHAR(45) NULL COMMENT '',
  `id_clientes` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_tb_faturas_tb_clientes1_idx` (`id_clientes` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_faturas_tb_clientes1`
    FOREIGN KEY (`id_clientes`)
    REFERENCES `u856889270_eedom`.`tb_clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = MyISAM DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `u856889270_eedom`.`tb_validacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u856889270_eedom`.`tb_validacao` ;

CREATE TABLE IF NOT EXISTS `u856889270_eedom`.`tb_validacao` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `chave` VARCHAR(32) NULL COMMENT '',
  `dt_cadastro` DATE NULL COMMENT '',
  `dt_validade` DATE NULL COMMENT '',
  `id_clientes` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_tb_validacao_tb_clientes1_idx` (`id_clientes` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_validacao_tb_clientes1`
    FOREIGN KEY (`id_clientes`)
    REFERENCES `u856889270_eedom`.`tb_clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = MyISAM DEFAULT CHARSET=utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into tb_admin (nome, email, senha) values ('Administrador', 'admin@admin.com.br', md5('123456'));